version: '3'
services:
  localstack:
    image: 'localstack/localstack:latest'
    ports:
    - '4566-4583:4566-4583'
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
      - EDGE_PORT=4566
    volumes:
      - '${TEMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
